name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      skip-lint:
        type: boolean
        description: 'Skip linting'
        required: false
        default: false
      skip-build:
        type: boolean
        description: 'Skip build'
        required: false
        default: false
    secrets:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        required: true

permissions:
  packages: write
  contents: read

jobs:
  lint:
    name: Run Linters and Formatters
    if: ${{ !inputs.skip-lint }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          reg_github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format

  build:
    name: Build & Test
    if: ${{ !inputs.skip-build }}
    needs: [lint]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ vars.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_APP_NAME: ${{ vars.NEXT_PUBLIC_APP_NAME }}
      NEXT_PUBLIC_APP_SHORT_NAME: ${{ vars.NEXT_PUBLIC_APP_SHORT_NAME }}
      NEXT_PUBLIC_APP_DESCRIPTION: ${{ vars.NEXT_PUBLIC_APP_DESCRIPTION }}
      NEXT_PUBLIC_APP_START_URL: ${{ vars.NEXT_PUBLIC_APP_START_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          reg_github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright Browsers
        run: pnpm playwright:install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
